kind: Namespace
apiVersion: v1
metadata:
  name: sample-python-project-web-namespace
  labels:
    app: sample-python-project-web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-project-web-deployment
  namespace: sample-python-project-web-namespace
  labels:
    app: sample-python-project-web
spec:
  replicas: 1 # this should be changed for non local environments
  selector:
    matchLabels:
      app: sample-python-project-web
  template:
    metadata:
      labels:
        app: sample-python-project-web
    spec:
      containers:
        - name: sample-python-project-web
          image: sample-python-project-web
          imagePullPolicy: Never # this is so we'll use our local image version
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 1
              memory: "128M"
            limits:
              cpu: 1
              memory: "128M"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          # env: - no env variables for now

---
apiVersion: v1
kind: Service
metadata:
  name: sample-python-project-web-service
  namespace: sample-python-project-web-namespace
  labels:
    app: sample-python-project-web
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sample-python-project-web
  type: LoadBalancer